name: finance_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.3.1
  shared_preferences: ^2.2.0
  fluro: ^2.0.5
  intl: ^0.17.0
  get_it: ^7.6.0
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/icon/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 600
